import sys
import os
import json 
import matplotlib.pyplot as plt 
import numpy as np
import statistics

WARNING = '\033[31m'
MASSAGE = '\033[32m'
text = '\033[37m'
block_count = []
total_forks = 0
node_fork = []
containers_list = os.popen('docker ps -aq').read()
containers_list = containers_list.splitlines()
num_container = len(containers_list)
containers_names_list = os.popen('docker ps --format {{.Names}}').read()#get containers names
containers_names_list = containers_names_list.splitlines()

#print(MASSAGE+'Preparing to generate performance report......')
#count number of blocks generated by each miner:
#print(MASSAGE+'Counting generated blocks......')
print("*******Simulation Report*******")


for x in xrange(0,num_container):
	 containers_names_list[x] = containers_names_list[x][27:32]
	 num_vaild_forks = os.popen('docker ' + 'exec ' + '-it ' + containers_list[x] + ' bitcoin-cli getchaintips | grep "valid-fork" | wc -l').read()
	 total_forks = total_forks + int(num_vaild_forks)
	 node_fork.append(num_vaild_forks)
	 nwallet_info = os.popen('docker ' + 'exec ' + '-it ' + containers_list[x] + ' bitcoin-cli getwalletinfo ').read()
	 nwallet_info = json.loads(nwallet_info)
	 txcount = nwallet_info["txcount"]
	 block_count.append(txcount)
print('Number of generated blocks by each miner:\n')
for x in xrange(0,num_container):
	print('%s miner: %s\n'%(containers_names_list[x],block_count[x]))
print('------------------------------------------')

print('Number of forks witnessed by each miner:\n')
for x in xrange(0,num_container):
	print('%s miner: %s'%(containers_names_list[x],node_fork[x]))
x_miners = list(range(1, num_container+1))
#get related mining info:
nmininginfo_info = os.popen('docker ' + 'exec ' + '-it ' + containers_list[0] + ' bitcoin-cli getmininginfo ').read()
nmininginfo_info = json.loads(nmininginfo_info)
networkhashps = nmininginfo_info["networkhashps"]
difficulty = nmininginfo_info["difficulty"]
#plot conf:
plt.figure(figsize=(20, 15)) 
plt.bar(containers_names_list,block_count,tick_label = containers_names_list,width = 0.8, color = ['green']) 
plt.yticks(np.arange(0,max(block_count)+10,10))
plt.xlabel('Miner') 
plt.ylabel('Number of generated Blocks (blk)') 
plt.title('Testnet Miners Perofmance')
#display the report:
print('------------------------------------------')
print('Total number of fork:%d')%(total_forks)
print('------------------------------------------')
print('Network hash per second:%s\nLatest difficulty:%s'%(networkhashps,difficulty))
print('------------------------------------------')
print('Avarage number of blocks generated by a miner:%d'%(statistics.mean(block_count)))
print('------------------------------------------')
print('Max number of blocks generated by a miner:%d'%(max(block_count)))
print('------------------------------------------')
print('Min number of blocks generated by a miner:%d'%(min(block_count)))
print('******************************************')
#plt.show()
plt.savefig('plot.png')
plt.close()



 

